name: naeemahmed
description: A new Flutter project focused only on Android.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  wakelock_plus: ^1.1.1
  win32: ^5.12.0
  carousel_slider: ^5.0.0
  provider: ^6.1.4
  http: ^1.3.0
  timeago: ^3.7.0
  cached_network_image: ^3.4.1
  intl: ^0.19.0
  flutter_markdown: ^0.7.7
  flutter_html: ^3.0.0
  cupertino_icons: ^1.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
